graph TD
    P_3V3_HP_SLOT1 --- CONN1
    P_12V_HP_SLOT1 --- CONN1
    P_3V3_AUX_HP_SLOT1 --- CONN1
    P_12V_HP_SLOT2 --- CONN2
    P_3V3_HP_SLOT2 --- CONN2
    P_3V3_AUX_HP_SLOT2 --- CONN2
    P_3V3_HP_SLOT3 --- CONN3
    P_3V3_AUX_HP_SLOT3 --- CONN3
    P_12V_HP_SLOT3 --- CONN3
    P_3V3_AUX_HP_SLOT4 --- CONN4
    P_3V3_HP_SLOT4 --- CONN4
    P_12V_HP_SLOT4 --- CONN4
    P_DDR4_VPP --- CONN5
    P_VDDQ_CPU --- CONN5
    P_12V --- CONN5
    P_0V6_VTT --- CONN5
    P_DDR4_VPP --- CONN6
    P_VDDQ_CPU --- CONN6
    P_12V --- CONN6
    P_0V6_VTT --- CONN6
    P_DDR4_VPP --- CONN7
    P_VDDQ_CPU --- CONN7
    P_12V --- CONN7
    P_0V6_VTT --- CONN7
    P_DDR4_VPP --- CONN8
    P_VDDQ_CPU --- CONN8
    P_12V --- CONN8
    P_0V6_VTT --- CONN8
    P_DDR4_VPP --- CONN9
    P_VDDQ_CPU --- CONN9
    P_12V --- CONN9
    P_0V6_VTT --- CONN9
    P_DDR4_VPP --- CONN10
    P_VDDQ_CPU --- CONN10
    P_12V --- CONN10
    P_0V6_VTT --- CONN10
    P_3V3 --- CONN11
    P_12V_NEG --- CONN11
    P_5V_SB --- CONN11
    P_12V --- CONN11
    P_5V --- CONN11
    P_3V3_CPLD --- CONN12
    P_3V3 --- FB1
    P_3V3_CLK_GEN_VDD --- FB1
    P_12V_PVCCIN_CPU --- FB2
    P_5V_DUAL --- FB3
    P_2V0_AQC1 --- FB4
    P0_V20_SERDES_MAT --- FB4
    P1_V20_SERDES_MAT --- FB5
    P_2V0_AQC2 --- FB5
    P_2V0_AQC2 --- FB6
    P1_2V0_R --- FB6
    P_2V0_AQC1 --- FB7
    P0_2V0_R --- FB7
    P_1V0_AQC2 --- FB8
    P1_VA10_R --- FB8
    P1_V20_SERDES --- FB9
    P_2V0_AQC2 --- FB9
    P_1V0_AQC1 --- FB10
    P0_VA10_R --- FB10
    P_2V0_AQC1 --- FB11
    P0_V20_SERDES --- FB11
    P_1V0_AQC2 --- FB12
    P1_V10_SERDES --- FB12
    P_1V0_AQC1 --- FB13
    P0_V10_SERDES --- FB13
    P_3V3_AQC2 --- FB14
    P1_VDD_IO_R --- FB14
    P_3V3_AQC1 --- FB15
    P0_VDD_IO_R --- FB15
    P1_VDD_08 --- FB16
    P0_VDD_08 --- FB17
    P_2V0_AQC2 --- FB18
    P1_VD20 --- FB18
    P_2V0_AQC1 --- FB19
    P0_VD20 --- FB19
    P_12V_PVCCANA --- FB20
    P_5V_DUAL --- FB20
    P_VCCNAC_DIGICK_FILT --- FB21
    P_1V05_NAC --- FB21
    P_1V05 --- FB22
    P_VCCDIGICKSI0_1P05 --- FB22
    P_1V05 --- FB23
    P_VCCCL_HSIO_1P05 --- FB23
    P_1V0_AQC1 --- L1
    P_2V0_AQC1 --- L2
    P_VDD_AQC1 --- L3
    P_3V3_HP_SLOT3 --- L4
    P_3V3_HP_SLOT2 --- L5
    P_2V0_AQC2 --- L6
    P_1V0_LAN --- L7
    P_3V3_HP_SLOT4 --- L8
    P_3V3_HP_SLOT1 --- L9
    P_3V3_UP --- L10
    P_1V0_AQC2 --- L11
    P_3V3_AQC1 --- L12
    P_VDD_AQC2 --- L13
    P_3V3_AQC2 --- L14
    P_DDR4_VPP --- L15
    P_VCCANA_CPU --- L16
    P_VNN_NAC --- L17
    P_1V05 --- L18
    P_VCCIN_CPU --- L19
    P_VCCIN_CPU --- L20
    P_VCCIN_CPU --- L21
    P_VNN_PCH --- L22
    P_3V3_AUX --- L23
    P_1V8 --- L24
    P_12V --- L25
    P_VDDQ_CPU --- L26
    P_VDDQ_CPU --- L27
    P_5V_DUAL --- L28
    P_12V_PVNN_PCH --- L28
    P_12V_PVCCIN_CPU --- L29
    P_12V --- L29
    P_5V_DUAL --- L30
    P_12V_PVNN_NAC --- L30
    P_1V05 --- Q17
    P_1V05 --- Q21
    P_5V_DUAL --- Q27
    P_12V --- Q27
    P_5V_SB --- Q28
    P5V_SB_BLEEDER --- Q28
    P_3V3_HP --- R37
    P_3V3_UP --- R37
    P_3V3_LAN --- R148
    P_3V3_UP --- R148
    P_3V3_AQC1 --- R199
    PVDD_AQC1_MODE --- R199
    P_3V3_AQC2 --- R335
    PVDD_AQC2_MODE --- R335
    P0V6_VTT_VOSNS --- R591
    P_0V6_VTT --- R591
    P_1V05 --- R593
    P_1V05_NAC --- R593
    P_1V05 --- R594
    P_1V05_NAC --- R594
    P_VDDQ_CPU --- R600
    P0V6_VTT_VLDOIN --- R600
    P_VDDQ_CPU --- R603
    P0V6_VTT_VLDOIN --- R603
    P_3V3_AUX --- R604
    P0V6_VTT_VIN --- R604
    P0V6_VTT_REFIN --- R607
    P0V6_VTT_VLDOIN --- R607
    P_1V8_CPU --- R796
    P_1V8 --- R796
    P_1V8_AUX --- R799
    P_1V8 --- R799
    PVCC_NACDELAY_1P8 --- R878
    P_1V8_AUX_NAC --- R878
    PVCC_NAC_1P8 --- R894
    P_1V8_AUX --- R894
    P_12V_PVCCIN_CPU --- R933
    P_5V_DUAL --- R933
    P_12V_PVCCIN_CPU --- R945
    P_5V_DUAL --- R945
    P_3V3_CLK_GEN_PLL --- R1181
    P_3V3_CLK_GEN_VDD --- R1181
    P_1V8_P3V3_AUX --- R1205
    P_1V8_AUX --- R1205
    P_1V8_P3V3_AUX --- R1206
    P_3V3_AUX --- R1206
    P_3V3_AUX --- R1207
    P_3V3_AUX_HSIO_OSC --- R1207
    P_3V3_AUX --- R1238
    P_3V3_AUX_BIOS --- R1238
    P_3V3_UP --- R1244
    P_3V3_CPLD --- R1244
    P_RTC_VCC --- R1286
    P_3V3_AUX --- R1286
    P_3V3_AUX --- U1
    P_3V3_AUX --- U2
    P_5V --- U3
    P_5V_USB3_P0 --- U3
    P_3V3_HP --- U4
    P_3V3_AUX --- U5
    P_1V0_AQC1 --- U6
    P_3V3_AQC1 --- U6
    P_2V0_AQC1 --- U7
    P_3V3_AQC1 --- U7
    P_5V_USB3_P1 --- U8
    P_5V --- U8
    P_3V3_LAN --- U9
    P_1V0_LAN --- U9
    P_12V_HP_SLOT3 --- U10
    P_12V_HP_SLOT2 --- U11
    P_12V --- U12
    P_12V_HP_SLOT3 --- U12
    P_12V_HP_SLOT2 --- U13
    P_12V --- U13
    P_12V_HP_SLOT4 --- U14
    P_12V_HP_SLOT1 --- U15
    P_3V3_AQC1 --- U16
    PVDD_AQC1_RAMP --- U16
    P_VDD_AQC1 --- U16
    PVDD_AQC1_MODE --- U16
    P_3V3_AQC2 --- U17
    P_2V0_AQC2 --- U17
    P_12V_HP_SLOT4 --- U18
    P_12V --- U18
    P_12V_HP_SLOT1 --- U19
    P_12V --- U19
    P_3V3_LAN --- U20
    P1_V20_SERDES --- U21
    P1_VA10_R --- U21
    P1_2V0_R --- U21
    P1_V10_SERDES --- U21
    P1_VDD_08 --- U21
    P_VDD_AQC2 --- U21
    P1_VD20 --- U21
    P1_V20_SERDES_MAT --- U21
    P1_VDD_IO_R --- U21
    P0_V20_SERDES --- U22
    P0_V20_SERDES_MAT --- U22
    P0_V10_SERDES --- U22
    P0_VA10_R --- U22
    P0_VDD_08 --- U22
    P0_VDD_IO_R --- U22
    P0_VD20 --- U22
    P_VDD_AQC1 --- U22
    P0_2V0_R --- U22
    P_5V_SB --- U23
    P_1V0_AQC2 --- U24
    P_3V3_AQC2 --- U24
    P_5V_DUAL --- U25
    P_3V3_AUX_HP_SLOT4 --- U26
    P_3V3_AUX --- U26
    P_3V3_AUX --- U27
    P_3V3_AUX_HP_SLOT1 --- U27
    P_3V3_AUX --- U28
    P_3V3_AUX_HP_SLOT3 --- U28
    P_3V3_AUX --- U29
    P_3V3_AUX_HP_SLOT2 --- U29
    PDDR4_VPP_VCC --- U30
    PDDR4_VPP_SS --- U30
    P_12V --- U30
    P_5V_DUAL --- U31
    P_3V3_AQC2 --- U32
    P_VDD_AQC2 --- U32
    PVDD_AQC2_MODE --- U32
    PVDD_AQC2_RAMP --- U32
    P_12V_PVCCANA --- U33
    P_3V3_AUX --- U34
    P_3V3_AUX --- U35
    P_DDR4_VPP --- U37
    P_1V05 --- U37
    P_12V_PVNN_NAC --- U38
    P_3V3_AUX --- U39
    P_3V3_CLK_GEN_PLL --- U40
    P_3V3_CLK_GEN_VDD --- U40
    P_12V_PVNN_PCH --- U41
    P_1V8_AUX --- U42
    P_1V8_CPU --- U42
    PVCC_NAC_1P8 --- U42
    P_VCCIN_CPU --- U42
    P_VNN_NAC --- U42
    P_VCCDIGICKSI0_1P05 --- U42
    P_1V8_P3V3_AUX --- U42
    P_VNN_PCH --- U42
    P_VDDQ_CPU --- U42
    PVCCRTC_EXT_CAP --- U42
    P_VCCCL_HSIO_1P05 --- U42
    P_3V3_AUX --- U42
    P_1V05 --- U42
    VSS_M61 --- U42
    P_3V3_RTC --- U42
    P_1V05_NAC --- U42
    P_VCCANA_CPU --- U42
    PVCC_NACDELAY_1P8 --- U42
    P_VCCNAC_DIGICK_FILT --- U42
    P_3V3_AUX --- U43
    P0V6_VTT_VOSNS --- U44
    P0V6_VTT_REFOUT --- U44
    P0V6_VTT_VIN --- U44
    P0V6_VTT_VLDOIN --- U44
    P0V6_VTT_REFIN --- U44
    P_0V6_VTT --- U44
    P_VDDQ_CPU --- U45
    P_3V3_AUX --- U46
    P_3V3_AUX --- U47
    P_12V_PVNN_PCH --- U51
    P_3V3_AUX_BIOS --- U52
    P_12V_PVCCIN_CPU --- U53
    P_5V --- U53
    P_12V_PVCCIN_CPU --- U54
    P_5V --- U54
    P_12V_PVCCIN_CPU --- U55
    P_5V --- U55
    P_5V_DUAL --- U56
    P_1V8_AUX --- U59
    P_1V8_AUX_NAC --- U59
    P_3V3_AUX --- U60
    P_3V3 --- U61
    P_3V3_AUX --- U63
    P_12V_PVDDQ --- U64
    P_12V_PVDDQ --- U65
    P_3V3_AUX --- U66
    P_3V3_AQC2 --- U67
    P_3V3_AQC1 --- U68
    P_3V3_CPLD --- U69
    P_3V3_AUX_BIOS --- U70
    P_3V3_AUX --- U71
    P_3V3_AUX_BIOS --- U71
    P_3V3_AUX --- U72
    P_3V3_UP --- U73
    P_3V3_CPLD --- U73
